### ISSUE TITLE
Doesn't work if environment variable POSTGRES_USER is different than postgres

### ISSUE THREAD

**Issue by ateuber** [justinclift/docker-pgautoupgrade#4]
I think the `pg_upgrade` statements just need a `-U username` each?

**Comment by justinclift** [comment]
I've just added `-U postgres` to each of the `pg_upgrade` lines: https://github.com/justinclift/docker-pgautoupgrade/commit/55b5cdb943315883833fbbfc87c49f2a9c64f5ea

I *think* that's what you were meaning, yeah? :smile:

Also just pushed an updated `dev` tagged image to Docker Hub, so you can try it out directly. :smile:

**Comment by justinclift** [comment]
Hmmm, I wonder if we need to force the username when we run `postgres` in single user mode for the collation check too?  Might investigate that a bit later on. :smile:
